name: Multi-Year 3D Scan

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-annual-3d-contribs
    steps:
      - uses: actions/checkout@v3
      
      # 2023 Scan
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          YEAR: 2023
      - run: mv profile-3d-contrib profile-2023

      # 2024 Scan
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          YEAR: 2024
      - run: mv profile-3d-contrib profile-2024

      # 2025 Scan
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          YEAR: 2025
      - run: mv profile-3d-contrib profile-2025

      # 2026 (Current) Scan
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          YEAR: 2026
      - run: mv profile-3d-contrib profile-2026

      - name: Commit & Push All
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update Multi-Year Laboratory Inventory" || echo "No changes"
          git push origin main
